export const CART_ACTIONS_TYPE = {
    FETCH_CART_START: 'FETCH_CART_START',
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    FETCH_CART_FAILED: 'FETCH_CART_FAILED',
    ADD_CART_START: "ADD_CART_START",
    ADD_CART_SUCCESS: "ADD_CART_SUCCESS",
    ADD_CART_FAILD: "ADD_CART_FAILD",
    SET_PRODUCTSID: "SET_PRODUCTSID",
}
